version: 2

commands:
  open_browser:
    parameters:
      browser:
        type: string
        default: "google-chrome"
      background:
        type: string
        default: "true"
    steps:
      - run:
          command: "<<parameters.browser>> '{url}'"
          background: "<<parameters.background>>"

  open_zen_flatpak:
    steps:
      - run:
          command: "flatpak run io.github.zen_browser.zen --new-tab '{url}'"
          background: "true"

  save_markdown:
    parameters:
      output_dir:
        type: string
        default: "~/Documents/ReadLater"
    steps:
      - run: "go-read-md --output <<parameters.output_dir>> '{url}'"

  save_html_markdown:
    parameters:
      output_dir:
        type: string
        default: "~/Documents/ReadLater"
    steps:
      - run: "go-read-html --output <<parameters.output_dir>> --url '{url}' --input '{html}'"

jobs:
  default_firefox:
    steps:
      - open_browser:
          browser: "firefox"

  social_zen:
    steps:
      - open_zen_flatpak

  read_markdown:
    steps:
      - save_markdown

  read_html:
    steps:
      - save_html_markdown

workflows:
  smart_routing:
    jobs:
      # 1. URL to Markdown (Reading list)
      - read_markdown:
          match: "(?i)(medium\\.com|generic-blog\\.com)"

      # 2. Chrome to Zen (Video/Social)
      - social_zen:
          match: "(?i)(youtube\\.com|twitch\\.tv)"

      # 3. Default: Chrome to Firefox
      - default_firefox:
          match: ".*"
